### PR TITLE
Reicast - Fix building Odroid-XU4 on newer Ubuntu kernels.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by joolswills** [comment]
Why a new line rather than removing 4 from the other line for example?

**Comment by joolswills** [comment]
Reicast is currently disabled on Mali as you may be aware so that will need changing too after confirmation of it being ok with the c1 also.

**Comment by ghost** [comment]
Yes, I was able to build and run it on XU4 without a problem by removing the !mali flag, but I don't have a c1 to test on (and wasn't aware that was the reason it was disabled, which makes sense).

No particular reason for the way I did it, just didn't think of it the other way.

**Comment by ghost** [comment]
Also, just for your awareness, I've been documenting various issues with RetroPie on Odroid XU4 along with fixes and workarounds for various issues here: https://retropie.org.uk/forum/topic/15375/adventures-with-odroid-xu4-and-retropie

I didn't want to flood you with bug reports and was hoping others might participate but doesn't seem there are many out there on it right now.

**Comment by joolswills** [comment]
It's primarily disabled as I didn't have the time to test on XU and C1 when doing the Mali ports etc. It's probably worth sending this patch upstream - as this branch was primarily made for the RPI (The logic can be changed in the module to use upstream repo for the XU3/4).

**Comment by ghost** [comment]
Okay, I'll send the patch upstream. Looks unlikely we'll see a merge anytime soon however. Thanks again.

**Comment by joolswills** [comment]
Thanks. Yep you may be right. I can include a patch until then in this repo.

**Comment by ghost** [comment]
Thanks, I'd appreciate it.

**Comment by ghost** [comment]
Just got merged upstream. It's a Christmas miracle.

**Pull request closed without merging**
