### PR TITLE
Multiplayers with configuration file

### PR DESCRIPTION
**Pull request by Hyell**
In emu.cfg, you can add : 
[players]
nb = 2 // 1 to 4 players

Reicast will add Sega Controller for each players. 
Note : you have to connect and configure each controller if you want play in multiplayer

### CODE REVIEW

**Comment by gizmo98** [comment]
Sounds good. In addition the reicast startup script must be modified so nb = x will be set at startup. You should post this fix upstream as well so we can switch upstream anytime in the future again.

**Comment by gizmo98** [comment]
https://github.com/reicast/reicast-emulator/issues/919 
https://github.com/RetroPie/RetroPie-Setup/issues/1407#issuecomment-206617299

**Comment by gizmo98** [comment]
@Hyell You should do a PR to RetroPie:retropie instead of RetroPie:master. We build reicast from this branch.

**Comment by gizmo98** [comment]
Ok. It runs fine if startup script is modified. 
@joolswills should this fix be merged here or should we wait if something happens upstream?

**Comment by Hyell** [comment]
Hello,

I do a second PR for retropie branch : https://github.com/RetroPie/reicast-emulator/pull/2
I will do modification on  the reicast startup script this week

**Comment by joolswills** [comment]
Probably should be sent upstream really and we can update our branch. Perhaps we can just include our minor patches in the module so we can avoid having to maintain a repository (depending on how active upstream development is)

**Comment by gizmo98** [comment]
Reicast upstream development is really slow. There are four commits this year but there are also 18 open PRs. 
@Hyell you should try to get this PR included upstream. If this PR will not be merged until next retropie release the fix should be merged in our branch.

**Comment by Hyell** [comment]
Hello, 
Retropie script have been change : 
https://github.com/RetroPie/RetroPie-Setup/pull/1483

**Pull request closed without merging**
