### PR TITLE
Upstream commits and dispmanx video driver

### PR DESCRIPTION
**Pull request by gizmo98**
Reicast development is really slow. There are 14 open PRs. Some are from 2015. This PR contains two upstream commits and dispmanx and omx drivers from OrN. OrN wanted to push his branch upstream. https://github.com/OrN/reicast-emulator/commit/174ee1b971cc3f7b5a1e093fa9c22b4e833e3db1#commitcomment-17480094

-fix sprite issues https://github.com/reicast/reicast-emulator/pull/927
-fix sound issues https://github.com/reicast/reicast-emulator/pull/926
-add dispmanx and omx driver for better performance

The dispmanx driver render resolution is 640x480. It is no longer necessary to switch output resolution to get better performance.

### CODE REVIEW

**Comment by gizmo98** [comment]
@joolswills 
Can this be merged as well or should we wait if dispmanx and omx support will be merged upstream?

**Comment by joolswills** [comment]
I must have missed this PR - lets merge it now then (Please feel free to merge if it's ready) and I will rebuild the binaries

**Comment by joolswills** [comment]
(and thanks again! :-) )

**Comment by gizmo98** [comment]
All right! I have played around with this for a while now and had no issues.

**Comment by dankcushions** [comment]
this is great! the image is much crisper for me (dispmanx much better scaler than my TV!). however strange thing - i get a blinking terminal cursor in the bottom right or top right corner whilst the game is running.

**Comment by gizmo98** [comment]
I also get a blinking at the bottom left. I don't know how to remove it at the moment. This seems to be the only "serious" difference between the old and new source. It's not surprising because dispmanx renders just a window in front of the console. If the window does not fill the whole screen the console is visible.

It should be possible to add a black fullscreen dispmanx layer element between this window and the console so console will be hidden. I have not seen an implementation up to now.
https://info-beamer.com/blog/raspberry-pi-hardware-video-scaler

**Comment by gizmo98** [comment]
@joolswills 
Did you rebuild reicast as well? I have not tested it right now.

**Comment by joolswills** [comment]
I did.

**Comment by joolswills** [comment]
I actually rebuilt all main/optional packages a day or two ago.

**Comment by gizmo98** [comment]
Thanks! :+1

**Comment by joolswills** [comment]
If you have time - please download the 4.0-rc1 images and see if it all seems correct to you :-)

**Pull request merged**
